services:
  - type: web
    name: in-out-backend
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://joy123:joy123@cluster0.db75ghr.mongodb.net/in-out?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: "168ca8e08e5ebaf23b210089b71fb914c7aaa968471ad4124db85c8f31724ebb"
      - key: RAZORPAY_KEY_ID
        value: "rzp_test_RdEbrAgSxi8vul"
      - key: RAZORPAY_KEY_SECRET
        value: "qC9iRGDdBqWWo6Bo7AivZp4Z"